
services:
  backend:
    container_name: creddie_backend
    image: creddie-backend:latest
    build:
      context: ./backend
    volumes:
      - type: bind
        source: ${PATH_TO_DB}
        target: /app/mnt
    env_file:
      - .env
    environment: # Overwrite .env file which locally will have path to dev db on your machine
      DATABASE_URI: "sqlite:////app/mnt"
    ports:
      - 8080:8080

  frontend:
    container_name: creddie_frontend
    image: creddie-frontend:latest
    build:
      context: ./frontend
    ports:
      - 8081:8081

volumes:
  myapp: