"""created category table. txn refs category.id

Revision ID: 1256d0839b58
Revises: ae297ff7a838
Create Date: 2024-10-27 15:38:01.907060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1256d0839b58'
down_revision: Union[str, None] = 'ca0b5484b1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('txncategories',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('txncategories')
    # ### end Alembic commands ###
