"""Transaction table creation.

Revision ID: ae297ff7a838
Revises: ca0b5484b1ea
Create Date: 2024-10-27 14:40:31.215026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae297ff7a838'
down_revision: Union[str, None] = 'ca0b5484b1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('entry_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('is_credit', sa.Boolean(), nullable=False),
    sa.Column('transaction_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('other_party', sa.String(length=64), nullable=False),
    sa.Column('transaction_description', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_gift', sa.Boolean(), nullable=False),
    sa.Column('gift_party', sa.String(length=64), nullable=False),
    sa.Column('is_marketplace', sa.Boolean(), nullable=False),
    sa.Column('marketplace_party', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
