"""Revision for temporary table only used to get things set up.

Revision ID: ca0b5484b1ea
Revises: 
Create Date: 2024-10-26 17:31:57.194149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0b5484b1ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Heros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('secret_name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Heros_age'), 'Heros', ['age'], unique=False)
    op.create_index(op.f('ix_Heros_name'), 'Heros', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Heros_name'), table_name='Heros')
    op.drop_index(op.f('ix_Heros_age'), table_name='Heros')
    op.drop_table('Heros')
    # ### end Alembic commands ###
